### PR TITLE
Sync fix from internal branch - Statistics

### PR DESCRIPTION
**Pull request by canhld94**
I hereby agree to the terms of the CLA available at: [placeholder]

Changelog category (leave one):
- Bug Fix
- Improvement

Detailed description / Documentation draft:

...

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ByConity Documentation](https://github.com/ByConity/ByConity/blob/master/CONTRIBUTING.md) guide first.

### CODE REVIEW

**Comment by canhld94** [comment]
Cannot find Guilin in the org yet, he should follow and review this PR

**Comment by canhld94** [comment]
@FluorineDog

**Comment by hustnn** [comment]
@canhld94 @FluorineDog duplicated with https://github.com/ByConity/ByConity/pull/112

**Comment by canhld94** [comment]
I will close this

**Pull request closed without merging**
