### PR TITLE
fix thread map

### PR DESCRIPTION
**Pull request by dmthuc**
I hereby agree to the terms of the CLA available at: [placeholder]

Changelog category (leave one):
- New Feature
- Bug Fix
- Improvement
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Other
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ByConity Documentation](https://github.com/ByConity/ByConity/blob/master/CONTRIBUTING.md) guide first.

### CODE REVIEW

**Comment by hustnn** [comment]
Trying to fix https://github.com/ByConity/ByConity/issues/123

**Comment by vivek-debug** [comment]
Shall we support the feature at a later date?

**Review by vivek-debug — APPROVED** [review]
LGTM. Added the required class but not used at the moment.

**Comment by vivek-debug** [comment]
cc @hustnn

**Pull request merged**
