### PR TITLE
fix the issue_301, byconity crash if query argument is null.

### PR DESCRIPTION
**Pull request by zhaojintaozhao**
fix the https://github.com/ByConity/ByConity/issues/301, byconity crash if query argument is null.

Add more judgments to avoid null variable in the where conditions of cnchhive queries.

### CODE REVIEW

**Comment by zhaojintaozhao** [comment]
fix the issue #301

**Comment by zhaojintaozhao** [comment]
> [CLA assistant check](https://cla-assistant.io/ByConity/ByConity?pullRequest=303) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ByConity/ByConity?pullRequest=303) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ByConity/ByConity?pullRequest=303) it.

I have signed the CLA.

**Comment by hustnn** [comment]
> > [CLA assistant check](https://cla-assistant.io/ByConity/ByConity?pullRequest=303) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ByConity/ByConity?pullRequest=303) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ByConity/ByConity?pullRequest=303) it.
> 
> I have signed the CLA.

hi @zhaojintaozhao , you can click the CLA button to sign it.

**Comment by zhaojintaozhao** [comment]
> [CLA assistant check](https://cla-assistant.io/ByConity/ByConity?pullRequest=303) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ByConity/ByConity?pullRequest=303) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ByConity/ByConity?pullRequest=303) it.

Hi, I have signed the CLA already but the status is still pending. Why?

**Comment by zhaojintaozhao** [comment]
> 

Hi hustnn, I have signed the CLA already but the status is still pending. What should I do?

**Review by Clark0 — APPROVED** [review]

**Review by Clark0 — APPROVED** [review]

**Comment by hustnn** [comment]
Thanks @zhaojintaozhao

**Pull request merged**
