### PR TITLE
Move documentation files to the `/docs` folder

### PR DESCRIPTION
**Pull request by pswai**
I hereby agree to the terms of the CLA available at: [placeholder]

Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Move documentation files to the `/docs` folder.
...

Detailed description / Documentation draft:
- The docs will be in the `/docs/<locale>` folders.
- They are currently duplications of existing files and should be translated accordingly.
- Recommend for any contributor to change them to use English file names for better path generation.
...

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ByConity Documentation](https://github.com/ByConity/ByConity/blob/master/CONTRIBUTING.md) guide first.

### CODE REVIEW

**Comment by vivek-debug** [comment]
Hi, can you rebase your PR on top of the master branch? We have made some fixes to CI there :)

**Comment by pswai** [comment]
> Hi, can you rebase your PR on top of the master branch? We have made some fixes to CI there :)

Sure, hang on

**Comment by pswai** [comment]
@vivek-debug Done, can you help taking a look?

**Comment by vivek-debug** [comment]
Seems like the CI has passed

**Review by vivek-debug — APPROVED** [review]

**Pull request merged**
