### PR TITLE
feat: Fix unstable test cases

### PR DESCRIPTION
**Pull request by vivek-debug**
### Changelog category :
- Testing Improvement. Related to #237 

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

- Fix unstable test cases
- Add retry for timeout cases
- Add multi-worker setup for all test suites

### CODE REVIEW

**Comment by vivek-debug** [comment]
@FluorineDog We have enabled multi-worker setup for all CI jobs and most of the failing test cases are coming from "Run CNCH FunctionalStateless with optimizer" job. Can i get yours and the optimizer team help to look into the failing test cases? If some are problematic we can disable them

**Comment by vivek-debug** [comment]
@hustnn @dmthuc @canhld94 You can add you test case fixes here

**Comment by hustnn** [comment]
I think we can separate the no more package fix to let it merge first.

**Comment by vivek-debug** [comment]
> I think we can separate the no more package fix to let it merge first.

Summary of changes:
1. "No more packets available" error fixed and retry added for it just in case
2. 00906 test case fixed
3. disabled join test cases for now
4. moved other unstable clickhouse_sql test cases to unstable folder

**Comment by hustnn** [comment]
> * disabled join test cases for now
> * moved other unstable clickhouse_sql test cases to unstable folder

Can you help to create a issue to track the the disabled cases?  In case we forget it Thanks.

**Review by hustnn — APPROVED** [review]

**Pull request merged**
