### PR TITLE
fix rpc service use ipv6

### PR DESCRIPTION
**Pull request by chenbay**
### Changelog category :
- Bug Fix

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
link to issue.   https://github.com/ByConity/ByConity/issues/235 
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by canhld94** [comment]
Please sign the CLA, thanks!

**Comment by chenbay** [comment]
> Please sign the CLA, thanks!

ok

**Comment by hustnn** [comment]
I am curious why it has issue for CI, do we use ipv6 in our ci? @vivek-debug

**Comment by chenbay** [comment]
> I am curious why it has issue for CI, do we use ipv6 in our ci? @vivek-debug

@hustnn i have fix it. let's try again

**Review by dmthuc — APPROVED** [review]

**Pull request merged**
