### PR TITLE
Sync from internal - fix optimizer arrayjoin with limit issue

### PR DESCRIPTION
**Pull request by canhld94**
Changelog category (leave one):
- New Feature
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

Detailed description / Documentation draft:

...

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ByConity Documentation](https://github.com/ByConity/ByConity/blob/master/CONTRIBUTING.md) guide first.

### CODE REVIEW

**Comment by canhld94** [comment]
Tao Wang (@wangtZJU) should review and follow-up this MR

**Comment by hustnn** [comment]
build failed.

**Comment by WillemJiang** [comment]
@canhld94 Could you provide more context information about why and how you made these changes?
It will help reviewer to understand the change.

**Comment by canhld94** [comment]
Fix builts, this is a fix from internal for `ARRAY JOIN`

**Review by hustnn — APPROVED** [review]

**Pull request merged**
